PL/Controllers/AlumnoMateriaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PL.Controllers
{
    public class AlumnoMateriaController : Controller
    {
        //
        // GET: /AlumnoMateria/
        public ActionResult GetAll()
        {
            ML.Alumno alumno = new ML.Alumno();
            ML.Result result = BL.Alumno.GetAll();
            alumno.Alumnos = result.Objects;
            return View(alumno);
        }

        public ActionResult MateriaGetAsignados(int IdAlumno)
        {
            ML.AlumnoMateria alumnoMateria = new ML.AlumnoMateria();
            alumnoMateria.Alumno = new ML.Alumno();
            alumnoMateria.Materia = new ML.Materia();
            ML.Result result = BL.AlumnoMateria.MateriaGetAsignados(IdAlumno);
            ML.Result resultAlumno = BL.Alumno.GetById(IdAlumno);
            alumnoMateria.AlumnoMaterias = result.Objects;
            alumnoMateria.Alumno = ((ML.Alumno)resultAlumno.Object);
            return View(alumnoMateria);
        }

        public ActionResult Delete(int IdAlumnoMateria, int IdAlumno)
        {
            ML.AlumnoMateria alumnoMateria = new ML.AlumnoMateria();
            alumnoMateria.IdAlumnoMateria = IdAlumnoMateria;
            ML.Result result = BL.AlumnoMateria.Delete(IdAlumnoMateria);
            ViewBag.MateriasAsignadas = true;
            ViewBag.IdAlumno = IdAlumno;
            if (result.Correct)
            {
                ViewBag.Mensaje = "La materia asignada se ha eliminado correctamente";
            }
            else
            {
                ViewBag.Mensaje = "La materia no se ha eliminado correctamente" + result.Ex;
            }
            return PartialView("ModalPV");
        }


        [HttpGet]
        public ActionResult MateriaGetNoAsignados(int IdAlumno)
        {
            ML.AlumnoMateria alumnoMateria = new ML.AlumnoMateria();
            alumnoMateria.Alumno = new ML.Alumno();
            alumnoMateria.Materia = new ML.Materia();
            ML.Result result = BL.AlumnoMateria.MateriaGetNoAsignados(IdAlumno);
            ML.Result resultAlumno = BL.Alumno.GetById(IdAlumno);
            alumnoMateria.AlumnoMaterias = result.Objects;
            alumnoMateria.Alumno = ((ML.Alumno)resultAlumno.Object);
            return View(alumnoMateria);
        }



        [HttpPost]
        public ActionResult MateriaGetNoAsignados(ML.AlumnoMateria alumnoMateria)
        {
            ML.Result result = new ML.Result();
            if (alumnoMateria.AlumnoMaterias != null)
            {
                foreach (string IdMateria in alumnoMateria.AlumnoMaterias)
                {
                    ML.AlumnoMateria alumnos = new ML.AlumnoMateria();

                    alumnos.Alumno = new ML.Alumno();
                    alumnos.Alumno.IdAlumno = alumnoMateria.Alumno.IdAlumno;

                    alumnos.Materia = new ML.Materia();
                    alumnos.Materia.IdMateria = int.Parse(IdMateria);      
                    ML.Result resul = BL.AlumnoMateria.Add(alumnos);
                }
                result.Correct = true;
                ViewBag.Mensaje = "Las materias se han agregado correctamente";
                
            }
            else
            {
                result.Correct = false;
                ViewBag.Mensaje = "Las materias no se han agregado correctamente";

            }
            return PartialView("Modal");
        }



	}
}

PL/Views/AlumnoMateria/GetAll.cshtml
@model ML.Alumno
@{
    ViewBag.Title = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1>AlumnoMateria</h1>
        </div> 
    </div>

    <div class="row">
        <div class="col-md-10">
            <h4>Seleccione ( i ) para mostrar las materias del Alumno</h4>
        </div>
    </div>
    <center>
    <div class="row">
        <div class="col-lg-12">
            <table class="table table-bordered table-hover">
                <thead>
                    <tr>
                        <td>MOSTRAR</td>
                        <td>Nombre</td>
                        <td>ApellidoPaterno</td>
                        <td>ApellidoMaterno</td>
                    </tr>
                </thead>
                <tbody>

                    @foreach (ML.Alumno alumno in Model.Alumnos)
                    {
                        <tr>
                            <td><a class="btn btn-primary glyphicon glyphicon-info-sign" href="@Url.Action("MateriaGetAsignados", "AlumnoMateria", new { IdAlumno = alumno.IdAlumno })"></a></td>
                            <td>@alumno.Nombre</td>
                            <td>@alumno.ApellidoPaterno</td>
                            <td>@alumno.ApellidoMaterno</td>
                        </tr>
                    }
                </tbody>
            </table> 
        </div>
    </div>
    </center>



</div>

PL/Views/AlumnoMateria/MateriaGetAsignados.cshtml
@model ML.AlumnoMateria
@{
    ViewBag.Title = "MateriaGetAsignados";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <h1>Materias Asignadas</h1>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-10">
                        <h4>Seleccione ( + ) para asignar materias al alumno y ( x ) para eliminar una materia</h4>
                    </div>
                </div>

               <div class="row">
                   <div class="col-lg-12">
                       <div class="form-group hidden">
                           @Html.LabelFor(model => model.Alumno.IdAlumno, new { @class = "control-label col-md-2 hidden" })
                           <div class="col-md-3">
                               @Html.TextBoxFor(model => model.Alumno.IdAlumno, new { @class = "form-control hidden", @readonly = true })
                               @Html.ValidationMessageFor(model => model.Alumno.IdAlumno)

                           </div>
                       </div>
                       <div class="form-group">
                           <div class="row">
                               <div class="col-md-3">
                                   @Html.LabelFor(model => model.Alumno.Nombre, new { @class = "control-label" })
                               </div>
                           </div>
                           <div class="row">
                               <div class="col-md-3">
                                   @Html.TextBoxFor(model => model.Alumno.Nombre, new { @class = "form-control", @ReadOnly = "True" })
                                   @Html.ValidationMessageFor(model => model.Alumno.Nombre)
                                   
                               </div>
                           </div>
                           <div class="row">
                               <div class="col-md-3">
                                   @Html.LabelFor(model => model.Alumno.ApellidoPaterno, "Apellido Paterno", new { @class = "control-label" })
                               </div>
                           </div>
                           <div class="row">
                               <div class="col-md-3">
                                   @Html.TextBoxFor(model => model.Alumno.ApellidoPaterno, new { @class = "form-control", @ReadOnly = "True" })
                                   @Html.ValidationMessageFor(model => model.Alumno.ApellidoPaterno)
                               </div>
                           </div>
                           <div class="row">
                               <div class="col-md-3">
                                   @Html.LabelFor(model => model.Alumno.ApellidoMaterno, "Apellido Materno", new { @class = "control-label" })
                               </div>
                           </div>
                           <div class="row">
                               <div class="col-md-3">
                                   @Html.TextBoxFor(model => model.Alumno.ApellidoMaterno, new { @class = "form-control", @ReadOnly = "True" })
                                   @Html.ValidationMessageFor(model => model.Alumno.ApellidoMaterno)
                               </div>
                           </div>
                           <br />
                           <div class="row">
                               <div class="col-md-12">
                                   <a href="@Url.Action("MateriaGetNoAsignados", "AlumnoMateria", Model.Alumno) ">
                                       <img style="height: 40px; width: 40px;" align="right" src="~/img/agregar.PNG" />
                                   </a>
                               </div>
                           </div>
                       </div>
                   </div>
               </div>
                <br/>
                <div class="row">
                    <div class="col-lg-12">
                        <table class="table table-bordered table-responsive">
                            <thead>
                                <tr>
                       
                                    <td>IdAlumno</td>
                                    <td>IdMateria</td>
                                    <td>Nombre</td>
                                    <td>Apellido Paterno</td>
                                    <td>Apellido Materno</td>
                                    <td>NombreMateria</td>
                                    <td>Eliminar</td>
                                </tr>
                            </thead>
                            <tbody>
                    
                                @foreach (ML.AlumnoMateria alumnoMateria in Model.AlumnoMaterias)
                                {
                                    <tr>
                                        <td>@alumnoMateria.IdAlumno</td>
                                        <td>@alumnoMateria.IdMateria</td>
                                        <td>@alumnoMateria.Alumno.Nombre</td>
                                        <td>@alumnoMateria.Alumno.ApellidoPaterno</td>
                                        <td>@alumnoMateria.Alumno.ApellidoMaterno</td>
                                        <td>@alumnoMateria.Materia.Nombre</td>
                                        <td><a class="btn btn-danger glyphicon glyphicon-remove" href="@Url.Action("Delete", "AlumnoMateria", new { IdAlumnoMateria = alumnoMateria.IdAlumnoMateria , IdAlumno= alumnoMateria.IdAlumno })" onclick="return confirm('Estas seguro que deseas eliminar este registro?');"></a></td>
                                    </tr>
                                     @*<tr>
                                    <td><a class="btn btn-danger glyphicon glyphicon-trash" href="@Url.Action("MateriaGetNoAsignados", "AlumnoMateria", new { IdAlumno = alumnoMateria.IdAlumno })"></a></td>>
                                    </tr>*@
                        
                        
                                }
                   
                            </tbody>
                        </table>
                    </div>
                </div>
                <center>
                    <br />
                        <div class="form-group">
                            <div class="col-md-12">
                                @Html.ActionLink("Regresar", "GetAll", "AlumnoMateria", htmlAttributes: new { @class = "btn btn-danger btn-block" })
                            </div>
                        </div>
                </center>



            </div>

PL/Views/AlumnoMateria/MateriaGetNoAsignados.cshtml
@model ML.AlumnoMateria
@{
    ViewBag.Title = "MateriaGetNoAsignados";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row">
    <div class="col-md-12">
        <h1>MATERIAS</h1>
    </div>
</div>
<hr />
<div class="row">
    <div class="col-md-10">
        <h4>MARQUE LA CASILLAS EN LAS MATERIAS QUE DESEAS AGREGAR</h4>
    </div>
</div>

<div class="row">
        @using (Html.BeginForm("MateriaGetNoAsignados", "AlumnoMateria", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <div class="form-group hidden">
                @Html.LabelFor(model => model.Alumno.IdAlumno, new { @class = "control-label col-md-2 hidden" })
                <div class="col-md-3">
                    @Html.TextBoxFor(model => model.Alumno.IdAlumno, new { @class = "form-control hidden", @readonly = true })
                    @Html.ValidationMessageFor(model => model.Alumno.IdAlumno)
                </div>
            </div>
            
            <div class="form-group">
                <div class="row">
                    <div class="col-md-3">
                        @Html.LabelFor(model => model.Alumno.Nombre, new { @class = "control-label" })
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-3">
                        @Html.TextBoxFor(model => model.Alumno.Nombre, new { @class = "form-control", @ReadOnly = "True" })
                        @Html.ValidationMessageFor(model => model.Alumno.Nombre)
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-3">
                        @Html.LabelFor(model => model.Alumno.ApellidoPaterno, "Apellido Paterno", new { @class = "control-label" })
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-3">
                        @Html.TextBoxFor(model => model.Alumno.ApellidoPaterno, new { @class = "form-control", @ReadOnly = "True" })
                        @Html.ValidationMessageFor(model => model.Alumno.ApellidoPaterno)
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-3">
                        @Html.LabelFor(model => model.Alumno.ApellidoMaterno, "Apellido Materno", new { @class = "control-label" })
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-3">
                        @Html.TextBoxFor(model => model.Alumno.ApellidoMaterno, new { @class = "form-control", @ReadOnly = "True" })
                        @Html.ValidationMessageFor(model => model.Alumno.ApellidoMaterno)
                    </div>
                </div>
            </div>
            
            <div class="row" style="padding-top:30px">
                <div class="col-md-12">
                    <table class="table table-bordered">
                        <tr>
                            <th class="text-center">
                                Selecciona
                            </th>
                            <th class="text-center " scope="col">
                                Nombre
                            </th>
                            <th class="text-left" scope="col">
                                Costo
                            </th>
                        </tr>
                        @foreach (ML.AlumnoMateria alumnoMateria in Model.AlumnoMaterias)
                        {
                            <tr>
                                <td class="text-center hidden">
                                    @alumnoMateria.Materia.IdMateria
                                </td>
                                <td class="text-center">
                                    <input type="checkbox" value="@alumnoMateria.Materia.IdMateria" name="AlumnoMaterias">
                                </td>
                                <td class="text-left">
                                    @alumnoMateria.Materia.Nombre
                                </td>
                                <td class="text-left">
                                    @alumnoMateria.Materia.Costo
                                </td>
                            </tr>
                        }
                    </table>
                    <div class="form-group col-md-12">
                        <div class="text-center">
                            <input class="btn btn-success" type="submit" value="Guardar" />
                        </div>
                    </div>
                    <center>
                        <br />
                        <div class="form-group">
                            <div class="col-md-12">
                                @Html.ActionLink("Regresar", "MateriaGetAsignados", "AlumnoMateria", Model.Alumno, htmlAttributes: new { @class = "btn btn-danger btn-block" })
                            </div>
                        </div>
                    </center>
                </div>
            </div>
   
        }

</div>

PL/Views/AlumnoMateria/Modal.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="modal" tabindex="-1" role="dialog" id="modalValidacion">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Aviso</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>@ViewBag.Mensaje</h5>
            </div>
            <div class="modal-footer">
                @Html.ActionLink("Regresar", "GetAll", "AlumnoMateria", htmlAttributes: new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
</div>

<script>
    $('#modalValidacion').modal();
</script>

PL/Views/AlumnoMateria/ModalPV.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="modal" tabindex="-1" role="dialog" id="modalValidacion">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Aviso</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>@ViewBag.Mensaje</h5>
            </div>
            <div class="modal-footer">
                @if (ViewBag.MateriasAsignadas == true)
                {
                     <a class="btn btn-danger" href="@Url.Action("MateriaGetAsignados", "AlumnoMateria", new { IdAlumno = ViewBag.IdAlumno })"> Regresar</a>

                }
                else
                {
                      <a class="btn btn-danger" href="@Url.Action("MateriaGetAsignados", "AlumnoMateria", new { IdAlumno = ViewBag.IdAlumno })"> Regresar</a>

                }
                
            </div>
        </div>
    </div>
</div>

<script>
    $('#modalValidacion').modal();
</script>