PL/Controllers/AlumnoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PL.Controllers
{
    public class AlumnoController : Controller
    {
        //
        // GET: /Alumno/
        public ActionResult GetAll()
        {
            ML.Result result = BL.Alumno.GetAll();
            ML.Alumno alumno = new ML.Alumno();
            alumno.Roles = new ML.Roles();
            alumno.Alumnos = result.Objects;
            return View(alumno);
        }

        [HttpGet]
        public ActionResult Form(int? IdAlumno) //Add { Id null } //Update {Id > 0 }
        {
            ML.Alumno alumno = new ML.Alumno();
            alumno.Roles = new ML.Roles();
            ML.Result resultAlumno = BL.Alumno.GetAll();
            ML.Result resultRoles = BL.Roles.GetAll();
            if (IdAlumno == null)
            {
                alumno.Roles.Rols = resultRoles.Objects;
                return View(alumno);
            }
            else
            {
                
                ML.Result result = new ML.Result();
                result = BL.Alumno.GetById(IdAlumno.Value);
                if (result.Correct)
                {
                    alumno.Roles = new ML.Roles();
                    alumno = ((ML.Alumno)result.Object);
                    alumno.Alumnos = resultAlumno.Objects;
                    alumno.Roles.Rols = resultRoles.Objects;
                    return View(alumno);
                }
                else
                {

                }
            }
            return View();
        }

        [HttpPost]
        public ActionResult Form(ML.Alumno alumno)
        {
          
            ML.Result result = new ML.Result();
            if (ModelState.IsValid)
            {

                if (alumno.IdAlumno == 0)
                {
                    result = BL.Alumno.Add(alumno);
                    if (result.Correct)
                    {
                        ViewBag.Mensaje = "El alumno se ha registrado correctamente";
                    }
                    else
                    {
                        ViewBag.Mensaje = "El alumno no se ha registrado correctamente " + result.ErrorMessage;
                    }

                }
                else
                {
                    result = BL.Alumno.Update(alumno);
                    if (result.Correct)
                    {
                        ViewBag.Mensaje = "El alumno se ha actualizado correctamente";
                    }
                    else
                    {
                        ViewBag.Mensaje = "El alumno no se ha actualizado correctamente " + result.ErrorMessage;
                    }
                }
            }
            else
            {
                alumno = new ML.Alumno();

                ML.Result resultAlumno = BL.Alumno.GetAll();
                return View(alumno);

            }

            return PartialView("ModalPV");
        }

        public ActionResult Delete(int IdAlumno)
        {
            ML.Alumno alumno = new ML.Alumno();
            alumno.IdAlumno = IdAlumno;
            ML.Result result = BL.Alumno.Delete(IdAlumno);
            if (result.Correct)
            {
                ViewBag.Mensaje = "El alumno se ha eliminado correctamente";
            }
            else
            {
                ViewBag.Mensaje = "El alumno no se ha eliminado correctamente " + result.ErrorMessage;
            }

            return PartialView("ModalPV");
        }


	}
}

PL/Controllers/MateriaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace PL.Controllers
{
    public class MateriaController : Controller
    {
        //
        // GET: /Materia/
        public ActionResult GetAll()
        {
            ML.Materia resultMateria = new ML.Materia();
            resultMateria.Materias = new List<Object>();

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:1718/api/");

                var responseTask = client.GetAsync("Materia/GetAll");
                responseTask.Wait();

                var result = responseTask.Result;

                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<ML.Result>();
                    readTask.Wait();

                    foreach (var resultItem in readTask.Result.Objects)
                    {
                        ML.Materia resultItemList = Newtonsoft.Json.JsonConvert.DeserializeObject<ML.Materia>(resultItem.ToString());
                        resultMateria.Materias.Add(resultItemList);
                    }
                }
            }
            return View(resultMateria);
        }


        [HttpGet]
        public ActionResult Form(int? IdMateria) //Add { Id null } //Update {Id > 0 }
        {
            ML.Materia materia = new ML.Materia();

            ML.Result resultMateria = BL.Materia.GetAll();

            if (IdMateria == null)
            {
                return View(materia);
            }
            else
            {
                ML.Result result = new ML.Result();
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri("http://localhost:1718/api/");
                    var responseTask = client.GetAsync("Materia/GetById/" + IdMateria);
                    responseTask.Wait();

                    var resultAPI = responseTask.Result;
                    if (resultAPI.IsSuccessStatusCode)
                    {
                        var readTask = resultAPI.Content.ReadAsAsync<ML.Result>();
                        readTask.Wait();

                        ML.Materia resultItemList = new ML.Materia();
                        resultItemList = Newtonsoft.Json.JsonConvert.DeserializeObject<ML.Materia>(readTask.Result.Object.ToString());
                        result.Object = resultItemList;

                        materia = ((ML.Materia)result.Object);

                        return View(materia);
                    }
                    else
                    {

                    }
                }
            }
            return View();
        }





        [HttpPost]
        public ActionResult Form(ML.Materia materia)
        {
            char[] ValidacionMateria = System.Configuration.ConfigurationManager.AppSettings["ValidacionNombreMateria"].ToCharArray();
            foreach (char caracter in ValidacionMateria)
            {
                materia.Nombre = materia.Nombre.Replace(caracter.ToString(), "");
            }
            ML.Result result = new ML.Result();
            if (ModelState.IsValid)
            {
                if (materia.IdMateria == 0)
                {
                    using (var client = new HttpClient())
                    {
                        client.BaseAddress = new Uri("http://localhost:1718/api/");

                        //HTTP POST
                        var postTask = client.PostAsJsonAsync<ML.Materia>("Materia/Add", materia);
                        postTask.Wait();

                        var resultAseguradora = postTask.Result;
                        if (resultAseguradora.IsSuccessStatusCode)
                        {
                            ViewBag.Mensaje = "La materia se ha registrado correctamente";
                        }
                        else
                        {
                            ViewBag.Mensaje = "La materia no se ha registrado correctamente " + result.ErrorMessage;
                        }

                    }

                }
                else
                {
                    using (var client = new HttpClient())
                    {
                        client.BaseAddress = new Uri("http://localhost:1718/api/");

                        //HTTP POST
                        var postTask = client.PutAsJsonAsync<ML.Materia>("Materia/Update/" + materia.IdMateria, materia);
                        postTask.Wait();

                        var resultAseguradora = postTask.Result;
                        if (resultAseguradora.IsSuccessStatusCode)
                        {
                            ViewBag.Mensaje = "La materia se ha actualizado correctamente";
                        }
                        else
                        {
                            ViewBag.Mensaje = "La materia no se ha actualizado correctamente " + result.ErrorMessage;
                        }
                    }
                }
            }
            else
            {
                materia = new ML.Materia();

                ML.Result resultAlumno = BL.Materia.GetAll();
                return View(materia);

            }

            return PartialView("ModalPV");
        }



        public ActionResult Delete(int IdMateria)
        {
            ML.Materia materia = new ML.Materia();
            ML.Result resultMateria = new ML.Result();
            //aseguradora.IdAseguradora= IdAseguradora;   
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:1718/api/");

                //HTTP POST
                var postTask = client.DeleteAsync("Materia/Delete/" + IdMateria);
                postTask.Wait();

                var result = postTask.Result;

                if (result.IsSuccessStatusCode)
                {
                    ViewBag.Mensaje = "La materia se ha eliminado correctamente";
                }
                else
                {
                    ViewBag.Mensaje = "La materia no se ha eliminado correctamente " + resultMateria.ErrorMessage;
                }

                return PartialView("ModalPV");
            }

        }
    }
}

PL/Views/Materia/Form.cshtml
@model ML.Materia
@{
    ViewBag.Title = "Form";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h2>MATERIA</h2>
            <h5> INGRESE LOS DATOS DE LA MATERIA</h5>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <hr />
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            @using (Html.BeginForm("Form", "Materia", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                <div class="form-horizontal">
                    <div class="form-group">
                        <div class="col-md-6">
                            @Html.LabelFor(model => model.IdMateria, new { @class = "hidden" })
                            @Html.TextBoxFor(model => model.IdMateria, new { @class = "hidden form-control", autocomplete = "off" })
                            @Html.ValidationMessageFor(model => model.IdMateria)
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-6">
                            @Html.LabelFor(model => model.Nombre, new { @class = "", @id = "lblNombre" })
                            @Html.TextBoxFor(model => model.Nombre, new { @class = "form-control", @id = "txtNombre", @onkeypress = "return SoloLetras(this)" })
                            @Html.ValidationMessageFor(model => model.Nombre,null, new { @class = "text-danger", @style = "display:none", @id = "lblErrorNombre" })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-6">
                            @Html.LabelFor(model => model.Costo)
                            @Html.TextBoxFor(model => model.Costo, "{0:#.#}", new { @class = "form-control txtCosto", @id = "txtCosto", @onkeypress = "return SoloNumeros(this)" })
                            @Html.ValidationMessageFor(model => model.Costo, null, new { @class = "text-danger" })
                            @Html.LabelFor(model => model.Costo, new { @class = "text-danger", @style = "display:none", @id = "lblErrorCosto" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-6">
                            @Html.LabelFor(model => model.Creditos)
                            @Html.TextBoxFor(model => model.Creditos, "{0:#.#}", new { @class = "form-control txtCreditos", @id = "txtCreditos", @onkeypress = "return Numeros(this)" })
                            @Html.ValidationMessageFor(model => model.Creditos, null, new { @class = "text-danger" })
                            @Html.LabelFor(model => model.Creditos, new { @class = "text-danger", @style = "display:none", @id = "lblErrorCreditos" })
                        </div>
                    </div>


                    <div class="form-group">
                        <div class="col-md-3">
                            <input type="submit" value="Guardar" class="btn btn-success" />
                            @Html.ActionLink("Regresar", "GetAll", "Materia", htmlAttributes: new { @class = "btn btn-danger" })
                        </div>
                    </div>

                </div>
            }

        </div>

    </div>

</div>

<script src="../../Scripts/jquery-1.10.2.js" type="text/javascript"></script>
<script src="../../Scripts/jquery-1.10.2.min.js" type="text/javascript"></script>
<link href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css" rel="Stylesheet" type="text/css" />
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.6/jquery.min.js" type="text/javascript"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js" type="text/javascript"></script>

<script type="text/javascript">

    function SoloLetras(e) {
        var letra = e.onkeypress.arguments[0].key;
        if (/^[^0-9]+$/g.test(letra)) {
            $("#lblErrorNombre").hide();
            return true;
        }
        else {
            if (e.id == "txtNombre") {
                $("#lblErrorNombre").text('Solo se aceptan letras');
                $('#lblErrorNombre').css('display', 'block');
            }
            return false;
        }
    }

    function SoloNumeros(e) {
        var letra = e.onkeypress.arguments[0].key;
        if (!/[^0-9]/g.test(letra)) {
            $("#lblErrorCosto").hide();
            return true;
        }
        else {
            if (e.id == "txtCosto") {
                $("#lblErrorCosto").text('Solo se aceptan Numeros');
                $('#lblErrorCosto').css('display', 'block');
            }
            return false;

        }
    }

    function Numeros(e) {
        var letra = e.onkeypress.arguments[0].key;
        if (!/[^0-9]/g.test(letra)) {
            $("#lblErrorCreditos").hide();
            return true;
        }
        else {
            if (e.id == "txtCreditos") {
                $("#lblErrorCreditos").text('Solo se aceptan Numeros');
                $('#lblErrorCreditos').css('display', 'block');
            }
            return false;

        }
    }

    </script>

PL/Views/Materia/GetAll.cshtml
@model ML.Materia
@{
    ViewBag.Title = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">
    <div class="row">
        <div class="=col-md-12">
            <h2>MATERIAS</h2>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <h5>Seleccione (+) para registrar una Materia y (-) para eliminar una Materia</h5>
        </div>
    </div>
    <div class="row">
        <div class="col-md-1">

            @Html.ActionLink("+", "Form", "Materia", htmlAttributes: new { @class = "btn btn-success" })
        </div>
    </div>


    <div class="row">
        <div class="col-lg-12">
            <table class="table table-bordered table-responsive">
                <thead>
                    <tr>
                        <td>Editar</td>
                        <td class="hidden">IdMateria</td>
                        <td>Nombre</td>
                        <td>Costo</td>
                        <td>Creditos</td>
                        <td>Borrar</td>

                    </tr>
                </thead>
                <tbody>
                    @foreach (ML.Materia materia in Model.Materias)
                    {
                        <tr>
                            <td><a class="btn btn-warning glyphicon glyphicon-edit" href="@Url.Action("Form", "Materia", new { IdMateria = materia.IdMateria })"></a></td>
                            <td class="hidden">@materia.IdMateria</td>
                            <td>@materia.Nombre</td>
                            <td>@materia.Costo</td>
                            <td>@materia.Creditos</td>
                      
                            <td><a class="btn btn-danger glyphicon glyphicon-trash" href="@Url.Action("Delete", "Materia", new { IdMateria = materia.IdMateria })" onclick="return confirm('Estas seguro que deseas eliminar este registro?');"></a></td>


                        </tr>
                    }
                </tbody>

            </table>
        </div>
    </div>

</div>

PL/Views/Materia/ModalPV.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="modal" tabindex="-1" role="dialog" id="modalValidacion">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Aviso</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>@ViewBag.Mensaje</h5>
            </div>
            <div class="modal-footer">
                @Html.ActionLink("Regresar", "GetAll", "Alumno", htmlAttributes: new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
</div>

<script>
    $('#modalValidacion').modal();
</script>